[2024-12-15T22:11:07.118+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: covid_data_pipeline.store_data scheduled__2024-12-14T00:00:00+00:00 [queued]>
[2024-12-15T22:11:07.136+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: covid_data_pipeline.store_data scheduled__2024-12-14T00:00:00+00:00 [queued]>
[2024-12-15T22:11:07.136+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-12-15T22:11:07.161+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): store_data> on 2024-12-14 00:00:00+00:00
[2024-12-15T22:11:07.169+0000] {standard_task_runner.py:57} INFO - Started process 378 to run task
[2024-12-15T22:11:07.176+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'covid_data_pipeline', 'store_data', 'scheduled__2024-12-14T00:00:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/covid_pipeline_dag.py', '--cfg-path', '/tmp/tmpb8odkp8e']
[2024-12-15T22:11:07.182+0000] {standard_task_runner.py:85} INFO - Job 28: Subtask store_data
[2024-12-15T22:11:07.310+0000] {task_command.py:416} INFO - Running <TaskInstance: covid_data_pipeline.store_data scheduled__2024-12-14T00:00:00+00:00 [running]> on host efb61c2ab0bb
[2024-12-15T22:11:07.491+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='ctw2012105@@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='covid_data_pipeline' AIRFLOW_CTX_TASK_ID='store_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-14T00:00:00+00:00'
[2024-12-15T22:11:07.540+0000] {data_warehouse.py:56} INFO - Saving data to warehouse table: covid_daily_stats
[2024-12-15T22:11:07.541+0000] {data_warehouse.py:80} ERROR - Error saving to warehouse: 'str' object has no attribute 'strftime'
[2024-12-15T22:11:07.542+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/covid_pipeline_dag.py", line 145, in store_data
    warehouse.save_to_warehouse(df)
  File "/opt/airflow/src/storage/data_warehouse.py", line 59, in save_to_warehouse
    current_date = df['extraction_date'].iloc[0].strftime('%Y-%m-%d')
AttributeError: 'str' object has no attribute 'strftime'
[2024-12-15T22:11:07.568+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=covid_data_pipeline, task_id=store_data, execution_date=20241214T000000, start_date=20241215T221107, end_date=20241215T221107
[2024-12-15T22:11:07.592+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 28 for task store_data ('str' object has no attribute 'strftime'; 378)
[2024-12-15T22:11:07.646+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-12-15T22:11:07.686+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-15T23:46:28.907+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: covid_data_pipeline.store_data scheduled__2024-12-14T00:00:00+00:00 [queued]>
[2024-12-15T23:46:28.929+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: covid_data_pipeline.store_data scheduled__2024-12-14T00:00:00+00:00 [queued]>
[2024-12-15T23:46:28.933+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-12-15T23:46:28.961+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): store_data> on 2024-12-14 00:00:00+00:00
[2024-12-15T23:46:28.970+0000] {standard_task_runner.py:57} INFO - Started process 317 to run task
[2024-12-15T23:46:28.976+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'covid_data_pipeline', 'store_data', 'scheduled__2024-12-14T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/covid_pipeline_dag.py', '--cfg-path', '/tmp/tmpyb7nwoza']
[2024-12-15T23:46:28.984+0000] {standard_task_runner.py:85} INFO - Job 14: Subtask store_data
[2024-12-15T23:46:29.112+0000] {task_command.py:416} INFO - Running <TaskInstance: covid_data_pipeline.store_data scheduled__2024-12-14T00:00:00+00:00 [running]> on host 6cd16bdff3c4
[2024-12-15T23:46:29.299+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='ctw2012105@@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='covid_data_pipeline' AIRFLOW_CTX_TASK_ID='store_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-14T00:00:00+00:00'
[2024-12-15T23:46:29.363+0000] {data_warehouse.py:50} INFO - Database tables initialized successfully
[2024-12-15T23:46:29.363+0000] {data_warehouse.py:66} INFO - Saving data to warehouse table: covid_daily_stats
[2024-12-15T23:46:29.448+0000] {data_warehouse.py:92} INFO - Successfully saved 231 records to covid_daily_stats
[2024-12-15T23:46:29.448+0000] {python.py:194} INFO - Done. Returned value was: Data stored successfully
[2024-12-15T23:46:29.492+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=covid_data_pipeline, task_id=store_data, execution_date=20241214T000000, start_date=20241215T234628, end_date=20241215T234629
[2024-12-15T23:46:29.537+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-12-15T23:46:29.570+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
