[2024-12-15T22:11:07.099+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: covid_data_pipeline.store_data __airflow_temporary_run_2024-12-15T22:04:42.446554+00:00__ [queued]>
[2024-12-15T22:11:07.118+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: covid_data_pipeline.store_data __airflow_temporary_run_2024-12-15T22:04:42.446554+00:00__ [queued]>
[2024-12-15T22:11:07.120+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-12-15T22:11:07.145+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): store_data> on 2024-01-01 00:00:00+00:00
[2024-12-15T22:11:07.153+0000] {standard_task_runner.py:57} INFO - Started process 374 to run task
[2024-12-15T22:11:07.160+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'covid_data_pipeline', 'store_data', '__***_temporary_run_2024-12-15T22:04:42.446554+00:00__', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/covid_pipeline_dag.py', '--cfg-path', '/tmp/tmpsi0jcdrm']
[2024-12-15T22:11:07.166+0000] {standard_task_runner.py:85} INFO - Job 25: Subtask store_data
[2024-12-15T22:11:07.289+0000] {task_command.py:416} INFO - Running <TaskInstance: covid_data_pipeline.store_data __airflow_temporary_run_2024-12-15T22:04:42.446554+00:00__ [running]> on host efb61c2ab0bb
[2024-12-15T22:11:07.472+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='ctw2012105@@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='covid_data_pipeline' AIRFLOW_CTX_TASK_ID='store_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='__***_temporary_run_2024-12-15T22:04:42.446554+00:00__'
[2024-12-15T22:11:07.523+0000] {data_warehouse.py:56} INFO - Saving data to warehouse table: covid_daily_stats
[2024-12-15T22:11:07.526+0000] {data_warehouse.py:80} ERROR - Error saving to warehouse: 'str' object has no attribute 'strftime'
[2024-12-15T22:11:07.527+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/covid_pipeline_dag.py", line 145, in store_data
    warehouse.save_to_warehouse(df)
  File "/opt/airflow/src/storage/data_warehouse.py", line 59, in save_to_warehouse
    current_date = df['extraction_date'].iloc[0].strftime('%Y-%m-%d')
AttributeError: 'str' object has no attribute 'strftime'
[2024-12-15T22:11:07.551+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=covid_data_pipeline, task_id=store_data, execution_date=20240101T000000, start_date=20241215T221107, end_date=20241215T221107
[2024-12-15T22:11:07.573+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 25 for task store_data ('str' object has no attribute 'strftime'; 374)
[2024-12-15T22:11:07.589+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-12-15T22:11:07.649+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
